Login = "root"
External = "10.90.38.18"
HostIPs = ["10.90.38.18", "10.90.38.23", "10.90.39.3"]
ProxyAddress = "localhost"
MonitorPort = 10000
Simulation = "ServiceMedChain"
Servers = 3
Hosts = 5
Debug = 1
DebugTime = false
DebugColor = false
DebugPadding = true
RunWait = "2h"
Delay = 20
Bandwidth = 100
Suite = "Ed25519"
PreScript = ""
Tags = ""
