name: Go test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{matrix.platform}}
    env:
      LLVL: trace
    steps:
    - name: Set up Go ^1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test without coverage
      run: go test ./...